### ISSUE TITLE
Some headlines are not fully visible on mobile views

### ISSUE THREAD

**Issue by FieteOtto** [okfde/volksentscheid-transparenz.de#2]
![transparenz1](https://user-images.githubusercontent.com/16335479/58627389-696f6b80-82d7-11e9-9436-9d679cd7d65d.png)

**Comment by woleonard** [comment]
@FieteMax, vielen Dank für's Issue anlegen! Könntest du dir vielleicht auch einmal anschauen, ob du das direkt fixen kannst?

**Comment by jfilter** [comment]
Has been fixed at some point.
