### ISSUE TITLE
Überschrift zur Newsletter-Anmeldung sichtbar machen

### ISSUE THREAD

**Issue by stadine** [okfde/volksentscheid-transparenz.de#6]
Die Überschrift war mal weiß

<img width="324" alt="Bildschirmfoto 2019-08-08 um 18 52 03" src="https://user-images.githubusercontent.com/7421063/62721956-b07f8880-ba0d-11e9-8a4e-b22f9ff51ab2.png">

**Comment by jfilter** [comment]
fixed in https://github.com/okfde/volksentscheid-transparenz.de/commit/beaaa453fc907c17100083e4fce57966bc057872
